### ISSUE TITLE
governor does auto transport even when off

### ISSUE THREAD

**Issue by frank-zago** [BrokenRegistry/Rotp-Fusion#89]
Governor does auto transport under this conditions:

  - "auto transport" is off
  - "from max prod" is on

**Comment by frank-zago** [comment]
Note that none of the colonies were close to max either.

**Comment by BrokenRegistry** [comment]
It's both a very old bug and... a feature!
The feature:
The "from max prod" is independent from "auto transport". It's like a mini "auto transport". This is a feature added by Xilmi.
Note: When "auto transport" is on,  "from max prod" has no impact.
The BUG now:
In the graphic design tools, the names of the two options are swapped! :-/
I'll fix that and try to improve the description.

**Comment by BrokenRegistry** [comment]
Fixed

**Comment by frank-zago** [comment]
I don't think it's fixed.
Start a new game, set "from max prod" to on. As soon as the 1st colony is founded, auto transports will happen. According to the description, that shouldn't happen.

**Comment by BrokenRegistry** [comment]
Yes, it was a mess. When the second auto transport was added, not all method were renamed (probably to keep some backward compatibility). the result was quite confusing!
I gave more meaningful name to the function, and improved the help text to match what is done.
